using System.Security.Cryptography;
using System.Text.Json;
using System.Text.Json.Serialization;
using Nvidea.Core.Desktop;
namespace Nvidea.DemoPackageValidator;
internal static class Program
{
 const int MaxBytes=131072, MaxDepth=32, MaxSeconds=180;
 static readonly string[] Required=["invoke-context","durable-memory","tavily-research","browser-verify","permission-gate","nebius-background","architecture-proof"];
 static readonly string[] RequiredAssets=["README.md","LICENSE","docs/personal-ai-demo-eval.md","docs/personal-ai-adversarial-eval.md","docs/judging-evidence-verifier.md","tools/Nvidea.PersonalAiDemoEval/Nvidea.PersonalAiDemoEval.csproj","tools/Nvidea.PersonalAiAdversarialEval/Nvidea.PersonalAiAdversarialEval.csproj","tools/Nvidea.JudgingEvidenceVerifier/Nvidea.JudgingEvidenceVerifier.csproj"];
 static readonly Dictionary<string,string[]> Milestones=new(StringComparer.Ordinal){["invoke-context"]=[nameof(SessionEvidenceKind.NemotronInferenceCompleted)],["durable-memory"]=[nameof(SessionEvidenceKind.MemoryInfluencedInvocation)],["tavily-research"]=[nameof(SessionEvidenceKind.TavilyResearchCompletedWithCitations)],["browser-verify"]=[nameof(SessionEvidenceKind.BrowserPostStateVerified)],["permission-gate"]=[nameof(SessionEvidenceKind.ConsequentialApprovalGateExercised)],["nebius-background"]=[nameof(SessionEvidenceKind.NebiusBackgroundExecutionObserved)],["architecture-proof"]=[]};
 static readonly JsonSerializerOptions Strict=new(JsonSerializerDefaults.Web){MaxDepth=MaxDepth,UnmappedMemberHandling=JsonUnmappedMemberHandling.Disallow};
 public static async Task<int> Main(string[] a){try{if(a.Length==1&&a[0] is "--help" or "-h"){Console.WriteLine("Usage: Nvidea.DemoPackageValidator <repo-root> <manifest.json> [--output <summary.json>]");return 0;}var o=Args(a);var root=Path.GetFullPath(o.Root);if(!Directory.Exists(root))throw new InvalidDataException("Repository root does not exist.");var bytes=Read(o.Manifest);var m=Parse(bytes);var checks=Validate(root,m);var pass=checks.All(x=>x.Passed);var result=new Summary(2,pass,Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant(),m.MaxDurationSeconds,m.Beats.Sum(x=>x.DurationSeconds),m.Beats.Count,checks);var json=JsonSerializer.Serialize(result,new JsonSerializerOptions(JsonSerializerDefaults.Web){WriteIndented=true});Console.WriteLine(json);if(o.Output is not null)await Atomic(o.Output,json+Environment.NewLine);return pass?0:1;}catch(Exception e)when(e is ArgumentException or InvalidDataException or IOException or UnauthorizedAccessException or JsonException or NotSupportedException){Console.Error.WriteLine(JsonSerializer.Serialize(new Failure(2,false,Clean(e.Message))));return 1;}}
 static IReadOnlyList<Check> Validate(string root,Manifest m){var c=new List<Check>();c.Add(C("schema-version",m.SchemaVersion==2,"Schema version must be 2."));c.Add(C("duration-cap",m.MaxDurationSeconds is >0 and <=MaxSeconds&&m.Beats.Sum(x=>x.DurationSeconds)<=m.MaxDurationSeconds,"Demo must fit within 180 seconds."));var ids=new HashSet<string>(StringComparer.Ordinal);var idok=m.Beats.Count>0&&m.Beats.All(b=>Text(b.Id)&&b.Id.Length<=96&&b.DurationSeconds is >0 and <=MaxSeconds&&ids.Add(b.Id));c.Add(C("beat-identities",idok,"Beat IDs must be unique and bounded."));c.Add(C("required-demo-beats",idok&&Required.All(ids.Contains),"All required judging beats must exist."));c.Add(C("beat-execution-contracts",m.Beats.All(b=>b.PreflightDependencies.Count>0&&b.PreflightDependencies.All(Text)&&Text(b.FallbackPolicy)),"Every beat requires explicit preflight dependencies and a fail-closed fallback policy."));c.Add(C("session-milestone-contracts",m.Beats.All(b=>Milestones.TryGetValue(b.Id,out var x)&&x.SequenceEqual(b.ExpectedSessionMilestones,StringComparer.Ordinal)),"Each beat must declare exactly its trusted production SessionEvidenceKind name."));var paths=m.Beats.SelectMany(b=>b.FeaturePaths).Concat(m.Beats.SelectMany(b=>b.Evidence).Select(e=>e.Path)).Concat(m.Commands.Select(x=>x.ProjectPath)).ToArray();c.Add(C("safe-relative-paths",paths.All(SafePath),"Referenced paths must remain inside the repository."));c.Add(C("referenced-paths-exist",paths.Where(SafePath).All(p=>Exists(root,p)),"Referenced paths must exist."));c.Add(C("required-repository-assets",RequiredAssets.All(p=>Exists(root,p)),"Required README, license, evaluator docs, and evaluator projects must exist."));c.Add(C("evidence-classes",m.Beats.SelectMany(b=>b.Evidence).All(e=>e.EvidenceClass is "synthetic" or "local-live" or "provider-live" or "documentation"),"Evidence class must be explicit."));c.Add(C("provider-live-claims",m.Beats.All(b=>!b.RequiresProviderLive||b.Evidence.Any(e=>e.EvidenceClass=="provider-live")),"Provider-live claims require provider-live evidence."));c.Add(C("demo-commands",m.Commands.Count>0&&m.Commands.All(x=>Text(x.Label)&&SafePath(x.ProjectPath)&&Text(x.Command)&&x.Command.Contains(x.ProjectPath,StringComparison.OrdinalIgnoreCase)),"Commands must reference their declared safe project."));c.Add(C("manifest-secret-scan",Strings(m).All(x=>!LooksSecret(x)),"Manifest must not contain private keys, bearer tokens, API-key assignments, or common secret prefixes."));return c;}
 static IEnumerable<string> Strings(Manifest m){yield return m.Title;foreach(var b in m.Beats){yield return b.Id;yield return b.Label;yield return b.JudgeClaim;yield return b.FallbackPolicy;foreach(var x in b.ExpectedSessionMilestones)yield return x;foreach(var x in b.PreflightDependencies)yield return x;foreach(var x in b.FeaturePaths)yield return x;foreach(var e in b.Evidence){yield return e.EvidenceClass;yield return e.Path;yield return e.Claim;}}foreach(var x in m.Commands){yield return x.Label;yield return x.ProjectPath;yield return x.Command;}}
 static bool LooksSecret(string? s){if(string.IsNullOrWhiteSpace(s))return false;var x=s.ToLowerInvariant();return x.Contains("-----begin private key-----",StringComparison.Ordinal)||x.Contains("authorization: bearer ",StringComparison.Ordinal)||x.Contains("api_key=",StringComparison.Ordinal)||x.Contains("apikey=",StringComparison.Ordinal)||x.Contains("sk-",StringComparison.Ordinal);}
 static bool Text(string? s)=>!string.IsNullOrWhiteSpace(s)&&s.Length<=1024&&!s.Any(char.IsControl);
 static bool SafePath(string? p){if(!Text(p)||Path.IsPathRooted(p))return false;var s=p!.Replace('\\','/').Split('/',StringSplitOptions.RemoveEmptyEntries);return s.Length>0&&s.All(x=>x is not "." and not ".."&&!x.Contains(':'));}
 static bool Exists(string root,string p){var f=Path.GetFullPath(Path.Combine(root,p.Replace('/',Path.DirectorySeparatorChar)));return f.StartsWith(root.TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase)&&(File.Exists(f)||Directory.Exists(f));}
 static byte[] Read(string p){var i=new FileInfo(Path.GetFullPath(p));if(!i.Exists||i.Length<=0||i.Length>MaxBytes)throw new InvalidDataException("Manifest missing or too large.");return File.ReadAllBytes(i.FullName);}
 static Manifest Parse(byte[] b){using var d=JsonDocument.Parse(b,new JsonDocumentOptions{AllowTrailingCommas=false,CommentHandling=JsonCommentHandling.Disallow,MaxDepth=MaxDepth});Duplicates(d.RootElement);var m=JsonSerializer.Deserialize<Manifest>(b,Strict)??throw new InvalidDataException("Manifest invalid.");if(!Text(m.Title)||m.Beats is null||m.Commands is null||m.Beats.Count>64||m.Commands.Count>64)throw new InvalidDataException("Manifest shape invalid.");foreach(var x in m.Beats)if(x.FeaturePaths is null||x.Evidence is null||x.ExpectedSessionMilestones is null||x.PreflightDependencies is null||!Text(x.Label)||!Text(x.JudgeClaim)||!Text(x.FallbackPolicy)||x.FeaturePaths.Count>64||x.Evidence.Count>64||x.ExpectedSessionMilestones.Count>16||x.PreflightDependencies.Count>32)throw new InvalidDataException("Beat shape invalid.");return m;}
 static void Duplicates(JsonElement e){if(e.ValueKind==JsonValueKind.Object){var n=new HashSet<string>(StringComparer.Ordinal);foreach(var p in e.EnumerateObject()){if(!n.Add(p.Name))throw new InvalidDataException("Duplicate JSON property.");Duplicates(p.Value);}}else if(e.ValueKind==JsonValueKind.Array)foreach(var x in e.EnumerateArray())Duplicates(x);}
 static Options Args(string[] a){if(a.Length is not 2 and not 4||a.Length==4&&a[2]!="--output")throw new ArgumentException("Expected root, manifest and optional output.");return new(a[0],a[1],a.Length==4?a[3]:null);}
 static async Task Atomic(string p,string s){var f=Path.GetFullPath(p);Directory.CreateDirectory(Path.GetDirectoryName(f)??".");var t=f+".tmp-"+Guid.NewGuid().ToString("N");try{await File.WriteAllTextAsync(t,s);File.Move(t,f,true);}finally{if(File.Exists(t))File.Delete(t);}}
 static string Clean(string s){s=(s??"Validation failed.").ReplaceLineEndings(" ").Trim();return s.Length<=512?s:s[..512];}static Check C(string id,bool ok,string req)=>new(id,ok,req);
 sealed record Options(string Root,string Manifest,string? Output);sealed record Manifest(int SchemaVersion,string Title,int MaxDurationSeconds,IReadOnlyList<Beat> Beats,IReadOnlyList<Command> Commands);sealed record Beat(string Id,string Label,int DurationSeconds,string JudgeClaim,bool RequiresProviderLive,IReadOnlyList<string> ExpectedSessionMilestones,IReadOnlyList<string> PreflightDependencies,string FallbackPolicy,IReadOnlyList<string> FeaturePaths,IReadOnlyList<Evidence> Evidence);sealed record Evidence(string EvidenceClass,string Path,string Claim);sealed record Command(string Label,string ProjectPath,string Command);sealed record Check(string Id,bool Passed,string Requirement);sealed record Summary(int SchemaVersion,bool OverallPassed,string ManifestSha256,int DeclaredMaximumDurationSeconds,int PlannedDurationSeconds,int BeatCount,IReadOnlyList<Check> Checks);sealed record Failure(int SchemaVersion,bool OverallPassed,string FailureMessage);
}
