using System.Windows;
using Nvidea.Core.Desktop;

namespace Nvidea.Windows;

public partial class ApprovalDialog : Window
{
    public ApprovalDialog(BrowserApprovalPrompt prompt)
    {
        ArgumentNullException.ThrowIfNull(prompt);
        InitializeComponent();

        var summary = DesktopDisplayTextTrust.Canonicalize(
            prompt.Summary,
            DesktopDisplayTextTrust.MaxApprovalSummaryCharacters,
            "Browser action requires explicit approval.");

        var target = Uri.TryCreate(prompt.Target, UriKind.Absolute, out var targetUri)
            ? DesktopDisplayTextTrust.ProjectNavigationTarget(targetUri)
            : DesktopDisplayTextTrust.Canonicalize(
                prompt.Target,
                DesktopDisplayTextTrust.MaxApprovalTargetCharacters,
                "current browser context");

        ActionText.Text = $"{prompt.ActionKind}: {summary}";
        // Target/summary can originate from a page, model, or runtime observation. Keep that
        // provenance explicit so rendered text cannot masquerade as NVIDEA authority.
        TargetText.Text = $"Untrusted browser target: {target}";
        // ExactScope is generated by NVIDEA's approval policy and is intentionally rendered
        // verbatim: changing it for presentation would make the human see a different authority
        // string from the one that must be echoed to authorize the action.
        ScopeText.Text = prompt.ExactScope;
    }

    private void Approve_Click(object sender, RoutedEventArgs e)
    {
        DialogResult = true;
        Close();
    }

    private void Deny_Click(object sender, RoutedEventArgs e)
    {
        DialogResult = false;
        Close();
    }
}
