[CmdletBinding()]
param(
    [switch]$InstallChromium,
    [string]$Configuration = "Release",
    [string]$Filter = "BrowserObservedValueChromiumIntegrationTests"
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$testProject = Join-Path $repoRoot "tests/Nvidea.Core.Tests/Nvidea.Core.Tests.csproj"

if (-not (Test-Path $testProject -PathType Leaf)) {
    throw "NVIDEA test project not found at expected path: $testProject"
}

$dotnet = Get-Command dotnet -ErrorAction Stop
$version = (& $dotnet.Source --version).Trim()
if (-not $version.StartsWith("8.")) {
    throw "NVIDEA browser integration requires .NET 8 SDK; found '$version'."
}

Push-Location $repoRoot
try {
    Write-Host "Restoring NVIDEA test project..."
    & $dotnet.Source restore $testProject
    if ($LASTEXITCODE -ne 0) { throw "dotnet restore failed with exit code $LASTEXITCODE." }

    Write-Host "Building NVIDEA test project ($Configuration)..."
    & $dotnet.Source build $testProject --configuration $Configuration --no-restore
    if ($LASTEXITCODE -ne 0) { throw "dotnet build failed with exit code $LASTEXITCODE." }

    if ($InstallChromium) {
        $playwrightScript = Get-ChildItem -Path (Join-Path $repoRoot "tests/Nvidea.Core.Tests/bin/$Configuration/net8.0") -Filter "playwright.ps1" -Recurse -File | Select-Object -First 1
        if ($null -eq $playwrightScript) {
            throw "Playwright installer script was not generated by the build. Check Microsoft.Playwright package/build output."
        }

        Write-Host "Installing the Microsoft.Playwright Chromium revision pinned by the test project..."
        & $playwrightScript.FullName install chromium
        if ($LASTEXITCODE -ne 0) { throw "Playwright Chromium installation failed with exit code $LASTEXITCODE." }
    }

    $previousOptIn = $env:NVIDEA_RUN_BROWSER_INTEGRATION
    try {
        $env:NVIDEA_RUN_BROWSER_INTEGRATION = "1"
        Write-Host "Running opt-in browser integration tests with filter '$Filter'..."
        & $dotnet.Source test $testProject --configuration $Configuration --no-build --filter "FullyQualifiedName~$Filter" --logger "console;verbosity=normal"
        if ($LASTEXITCODE -ne 0) { throw "Browser integration tests failed with exit code $LASTEXITCODE." }
    }
    finally {
        $env:NVIDEA_RUN_BROWSER_INTEGRATION = $previousOptIn
    }
}
finally {
    Pop-Location
}
