[CmdletBinding()]
param(
    [switch]$InstallChromium,
    [switch]$SecuritySuite,
    [switch]$KeepResults,
    [string]$Configuration = "Release",
    [string]$Filter = "BrowserObservedValueChromiumIntegrationTests"
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$testProject = Join-Path $repoRoot "tests/Nvidea.Core.Tests/Nvidea.Core.Tests.csproj"

if (-not (Test-Path $testProject -PathType Leaf)) {
    throw "NVIDEA test project not found at expected path: $testProject"
}

if ($SecuritySuite -and $PSBoundParameters.ContainsKey("Filter")) {
    throw "Use either -SecuritySuite or -Filter, not both."
}

# Keep this list explicit: these fixtures cross the real Chromium boundary and cover
# the highest-risk transport/privacy/persistence/download/cancellation behavior.
$securitySuiteClasses = @(
    "BrowserObservedValueChromiumIntegrationTests",
    "BrowserDownloadChromiumIntegrationTests",
    "PersistentBrowserRedirectIntegrationTests",
    "PersistentBrowserSessionIntegrationTests",
    "PlaywrightInFlightCancellationIntegrationTests"
)

$effectiveFilter = if ($SecuritySuite) {
    ($securitySuiteClasses | ForEach-Object { "FullyQualifiedName~$_" }) -join "|"
}
else {
    "FullyQualifiedName~$Filter"
}

$dotnet = Get-Command dotnet -ErrorAction Stop
$version = (& $dotnet.Source --version).Trim()
if (-not $version.StartsWith("8.")) {
    throw "NVIDEA browser integration requires .NET 8 SDK; found '$version'."
}

Push-Location $repoRoot
try {
    Write-Host "Restoring NVIDEA test project..."
    & $dotnet.Source restore $testProject
    if ($LASTEXITCODE -ne 0) { throw "dotnet restore failed with exit code $LASTEXITCODE." }

    Write-Host "Building NVIDEA test project ($Configuration)..."
    & $dotnet.Source build $testProject --configuration $Configuration --no-restore
    if ($LASTEXITCODE -ne 0) { throw "dotnet build failed with exit code $LASTEXITCODE." }

    if ($InstallChromium) {
        $playwrightScript = Get-ChildItem -Path (Join-Path $repoRoot "tests/Nvidea.Core.Tests/bin/$Configuration/net8.0") -Filter "playwright.ps1" -Recurse -File | Select-Object -First 1
        if ($null -eq $playwrightScript) {
            throw "Playwright installer script was not generated by the build. Check Microsoft.Playwright package/build output."
        }

        Write-Host "Installing the Microsoft.Playwright Chromium revision pinned by the test project..."
        & $playwrightScript.FullName install chromium
        if ($LASTEXITCODE -ne 0) { throw "Playwright Chromium installation failed with exit code $LASTEXITCODE." }
    }

    $previousOptIn = $env:NVIDEA_RUN_BROWSER_INTEGRATION
    $resultsDirectory = Join-Path ([System.IO.Path]::GetTempPath()) ("nvidea-browser-tests-" + [Guid]::NewGuid().ToString("N"))
    $validationSucceeded = $false
    try {
        $env:NVIDEA_RUN_BROWSER_INTEGRATION = "1"
        New-Item -ItemType Directory -Path $resultsDirectory -Force | Out-Null
        if ($SecuritySuite) {
            Write-Host "Running curated Chromium security suite: $($securitySuiteClasses -join ', ')"
        }
        else {
            Write-Host "Running opt-in browser integration tests with filter '$Filter'..."
        }

        & $dotnet.Source test $testProject --configuration $Configuration --no-build --filter $effectiveFilter --results-directory $resultsDirectory --logger "trx;LogFileName=browser-integration.trx" --logger "console;verbosity=normal"
        if ($LASTEXITCODE -ne 0) { throw "Browser integration tests failed with exit code $LASTEXITCODE. Evidence retained at '$resultsDirectory'." }

        # dotnet test can exit successfully when a filter discovers zero tests, and adapters can
        # report skipped/not-executed results without proving the browser boundary. Treat both as
        # validation failures. For the curated gate, prove every required fixture actually passed.
        $trxPath = Join-Path $resultsDirectory "browser-integration.trx"
        if (-not (Test-Path $trxPath -PathType Leaf)) {
            throw "Browser integration test run produced no TRX evidence at '$trxPath'. Results directory retained at '$resultsDirectory'."
        }

        [xml]$trx = Get-Content -LiteralPath $trxPath -Raw
        $results = @($trx.TestRun.Results.UnitTestResult)
        if ($results.Count -eq 0) {
            throw "Browser integration filter '$effectiveFilter' produced zero test results. Refusing a false-positive validation pass. Evidence retained at '$resultsDirectory'."
        }

        $passed = @($results | Where-Object { [string]$_.outcome -eq "Passed" })
        if ($passed.Count -eq 0) {
            $outcomes = @($results | ForEach-Object { [string]$_.outcome } | Sort-Object -Unique) -join ", "
            throw "Browser integration produced no passed tests (outcomes: $outcomes). Skipped/not-executed evidence does not validate the Chromium boundary. Evidence retained at '$resultsDirectory'."
        }

        $nonPassed = @($results | Where-Object { [string]$_.outcome -ne "Passed" })
        if ($nonPassed.Count -gt 0) {
            $summary = @($nonPassed | ForEach-Object { "'$([string]$_.testName)'=$([string]$_.outcome)" }) -join "; "
            throw "Browser integration contains non-passed results: $summary. Refusing partial validation evidence. Evidence retained at '$resultsDirectory'."
        }

        if ($SecuritySuite) {
            $passedNames = @($passed | ForEach-Object { [string]$_.testName })
            foreach ($requiredClass in $securitySuiteClasses) {
                if (-not ($passedNames | Where-Object { $_ -like "*$requiredClass*" })) {
                    throw "Curated Chromium security fixture '$requiredClass' has no passed test evidence. Refusing an incomplete validation pass. Evidence retained at '$resultsDirectory'."
                }
            }
        }

        $validationSucceeded = $true
        Write-Host "Verified executable PASS evidence for all $($passed.Count) browser integration test result(s)."
        if ($KeepResults) {
            Write-Host "Keeping browser validation evidence at '$resultsDirectory'."
        }
    }
    finally {
        $env:NVIDEA_RUN_BROWSER_INTEGRATION = $previousOptIn
        # Failed security validation is forensic evidence: retain it by default so a developer can
        # inspect the exact TRX/output instead of rerunning a potentially timing-sensitive browser
        # failure. Successful runs remain ephemeral unless explicitly requested with -KeepResults.
        if ($validationSucceeded -and -not $KeepResults -and (Test-Path $resultsDirectory)) {
            Remove-Item -LiteralPath $resultsDirectory -Recurse -Force -ErrorAction SilentlyContinue
        }
        elseif ((Test-Path $resultsDirectory) -and -not $validationSucceeded) {
            Write-Warning "Browser validation did not complete successfully. Evidence retained at '$resultsDirectory'."
        }
    }
}
finally {
    Pop-Location
}
