[CmdletBinding()]
param(
    [string]$RepositoryRoot = (Split-Path -Parent $PSScriptRoot),
    [string]$ArtifactsDirectory = "artifacts/preflight"
)
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Assert-RepositoryFilePath {
    param([Parameter(Mandatory)][string]$Path,[Parameter(Mandatory)][string]$RepositoryPrefix)
    $full=[IO.Path]::GetFullPath($Path)
    if(-not $full.StartsWith($RepositoryPrefix,[StringComparison]::OrdinalIgnoreCase)){throw "Expected output must remain inside the repository: $full"}
    $full
}
function Get-Sha256Hex { param([Parameter(Mandatory)][string]$Path) (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant() }
function Assert-JsonRuntimePrerequisites {
    try {$t=[type]::GetType('System.Text.Json.JsonDocument, System.Text.Json',$false);if($null-eq$t){throw 'System.Text.Json unavailable.'};$null=[System.Text.Json.JsonDocumentOptions]::new()} catch {throw "Submission preflight requires PowerShell with System.Text.Json available (PowerShell 7+ recommended). Detail: $($_.Exception.Message)"}
}
function Assert-NoDuplicateJsonProperties { param([Parameter(Mandatory)][System.Text.Json.JsonElement]$Element,[Parameter(Mandatory)][string]$Label,[string]$JsonPath='$');if($Element.ValueKind-eq[System.Text.Json.JsonValueKind]::Object){$names=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal);foreach($p in $Element.EnumerateObject()){if(-not$names.Add($p.Name)){throw "$Label contains duplicate JSON property '$($p.Name)' at $JsonPath."};Assert-NoDuplicateJsonProperties $p.Value $Label "$JsonPath.$($p.Name)"}}elseif($Element.ValueKind-eq[System.Text.Json.JsonValueKind]::Array){$i=0;foreach($x in $Element.EnumerateArray()){Assert-NoDuplicateJsonProperties $x $Label "$JsonPath[$i]";$i++}}}
function Assert-AllowedProperties { param($Object,[string[]]$Allowed,[string]$Label,[string]$JsonPath);$allow=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal);foreach($n in $Allowed){$null=$allow.Add($n)};foreach($p in $Object.PSObject.Properties){if(-not$allow.Contains($p.Name)){throw "$Label contains unexpected JSON property '$($p.Name)' at $JsonPath."}}}
function Read-StrictEvidenceJson { param([string]$Path,[string]$Label);$item=Get-Item $Path;if($item.Length-gt1MB){throw "$Label exceeds 1 MiB."};$raw=Get-Content $Path -Raw -Encoding UTF8;try{$o=[System.Text.Json.JsonDocumentOptions]::new();$o.MaxDepth=64;$d=[System.Text.Json.JsonDocument]::Parse($raw,$o);try{Assert-NoDuplicateJsonProperties $d.RootElement $Label}finally{$d.Dispose()};$raw|ConvertFrom-Json -ErrorAction Stop}catch{throw "$Label produced invalid or ambiguous JSON: $($_.Exception.Message)"}}
function Assert-PassedEvidence { param([string]$Path,[string]$Label,[int]$ExpectedSchemaVersion,[ValidateSet('validator','evaluator')][string]$Kind='evaluator');$e=Read-StrictEvidenceJson $Path $Label;$top=if($Kind-eq'validator'){@('schemaVersion','overallPassed','manifestSha256','declaredMaximumDurationSeconds','plannedDurationSeconds','beatCount','checks')}else{@('schemaVersion','generatedAt','overallPassed','checks','metrics')};$check=if($Kind-eq'validator'){@('id','passed','requirement')}else{@('id','passed','detail')};Assert-AllowedProperties $e $top $Label '$';$i=0;foreach($c in @($e.checks)){Assert-AllowedProperties $c $check $Label "$.checks[$i]";$i++};if([int]$e.schemaVersion-ne$ExpectedSchemaVersion-or$e.overallPassed-isnot[bool]-or-not$e.overallPassed-or@($e.checks).Count-eq0){throw "$Label is not an explicit schema-valid PASS."};foreach($c in @($e.checks)){if([string]::IsNullOrWhiteSpace([string]$c.id)-or$c.passed-isnot[bool]-or-not$c.passed){throw "$Label contains a malformed/failed check."}};$e}
function Assert-ValidatorEvidence { param([string]$Path,[string]$ManifestPath);$e=Assert-PassedEvidence $Path 'Demo package validator' 2 validator;$m=Read-StrictEvidenceJson $ManifestPath 'Demo manifest';if(-not[string]::Equals([string]$e.manifestSha256,(Get-Sha256Hex $ManifestPath),[StringComparison]::OrdinalIgnoreCase)){throw 'Validator manifest SHA mismatch.'};if([int]$e.beatCount-ne@($m.beats).Count-or[int]$e.plannedDurationSeconds-ne(@($m.beats)|Measure-Object durationSeconds -Sum).Sum){throw 'Validator evidence does not match manifest.'}}
function Assert-ChecklistMatchesManifest { param([string]$Path,[string]$ManifestPath);$m=Read-StrictEvidenceJson $ManifestPath 'Demo manifest';$text=Get-Content $Path -Raw -Encoding UTF8;$matches=[regex]::Matches($text,'(?m)^##\s+(\d+)\.\s+(.+?)\s+\((\d+)s\)\s*$');if($matches.Count-ne@($m.beats).Count){throw 'Checklist beat count mismatch.'};for($i=0;$i-lt@($m.beats).Count;$i++){$b=@($m.beats)[$i];if([int]$matches[$i].Groups[1].Value-ne$i+1-or$matches[$i].Groups[2].Value-ne[string]$b.label-or[int]$matches[$i].Groups[3].Value-ne[int]$b.durationSeconds){throw "Checklist beat $($i+1) mismatch."};foreach($x in @($b.expectedSessionMilestones)){if(-not$text.Contains("``$x``",[StringComparison]::Ordinal)){throw "Checklist missing milestone '$x'."}}};if(-not$text.Contains('## Take acceptance gate',[StringComparison]::Ordinal)){throw 'Checklist missing take acceptance gate.'}}
function Invoke-CheckedDotnet { param([string[]]$Arguments,[string]$Label,[string]$ExpectedOutput,[string]$RepositoryPrefix);$out=Assert-RepositoryFilePath $ExpectedOutput $RepositoryPrefix;Remove-Item $out -Force -ErrorAction SilentlyContinue;& dotnet @Arguments;if($LASTEXITCODE-ne0){throw "$Label failed with exit code $LASTEXITCODE."};if(-not(Test-Path $out -PathType Leaf)-or(Get-Item $out).Length-le0){throw "$Label did not materialize a non-empty expected output."}}

Assert-JsonRuntimePrerequisites
$root=[IO.Path]::GetFullPath($RepositoryRoot);if(-not(Test-Path $root -PathType Container)){throw "Repository root does not exist: $root"};$manifest=Join-Path $root 'docs/demo-package.json';$receiptVerifier=Join-Path $root 'scripts/verify-preflight-receipt.ps1';if(-not(Test-Path $manifest -PathType Leaf)){throw 'Demo manifest is missing.'};if(-not(Test-Path $receiptVerifier -PathType Leaf)){throw 'Independent receipt verifier is missing.'};if(-not(Get-Command dotnet -ErrorAction SilentlyContinue)){throw '.NET 8 SDK is required.'}
$artifacts=if([IO.Path]::IsPathRooted($ArtifactsDirectory)){[IO.Path]::GetFullPath($ArtifactsDirectory)}else{[IO.Path]::GetFullPath((Join-Path $root $ArtifactsDirectory))};$rootPrefix=$root.TrimEnd([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar)+[IO.Path]::DirectorySeparatorChar;if(-not$artifacts.StartsWith($rootPrefix,[StringComparison]::OrdinalIgnoreCase)){throw 'ArtifactsDirectory must remain inside repository.'};New-Item -ItemType Directory $artifacts -Force|Out-Null
$runId=[Guid]::NewGuid().ToString('N');$started=[DateTimeOffset]::UtcNow;Push-Location $root
try{
 $validation=Join-Path $artifacts 'demo-package-validation.json';Invoke-CheckedDotnet @('run','--project','tools/Nvidea.DemoPackageValidator/Nvidea.DemoPackageValidator.csproj','--','.','docs/demo-package.json','--output',$validation) 'validator' $validation $rootPrefix;Assert-ValidatorEvidence $validation $manifest
 $checklist=Join-Path $artifacts 'recording-checklist.md';Invoke-CheckedDotnet @('run','--project','tools/Nvidea.DemoChecklistGenerator/Nvidea.DemoChecklistGenerator.csproj','--','docs/demo-package.json','--output',$checklist) 'checklist generator' $checklist $rootPrefix;Assert-ChecklistMatchesManifest $checklist $manifest
 $positive=Join-Path $artifacts 'personal-ai-positive.json';Invoke-CheckedDotnet @('run','--project','tools/Nvidea.PersonalAiDemoEval/Nvidea.PersonalAiDemoEval.csproj','--','--output',$positive) 'positive evaluator' $positive $rootPrefix;Assert-PassedEvidence $positive 'Positive evaluator' 1 evaluator|Out-Null
 $adversarial=Join-Path $artifacts 'personal-ai-adversarial.json';Invoke-CheckedDotnet @('run','--project','tools/Nvidea.PersonalAiAdversarialEval/Nvidea.PersonalAiAdversarialEval.csproj','--','--output',$adversarial) 'adversarial evaluator' $adversarial $rootPrefix;Assert-PassedEvidence $adversarial 'Adversarial evaluator' 1 evaluator|Out-Null
 $receipt=Assert-RepositoryFilePath (Join-Path $artifacts 'preflight-receipt.json') $rootPrefix;Remove-Item $receipt -Force -ErrorAction SilentlyContinue;$bound=@();foreach($p in @($validation,$checklist,$positive,$adversarial)){$item=Get-Item $p;$bound+=@{path=[IO.Path]::GetRelativePath($root,$p).Replace('\','/');sha256=Get-Sha256Hex $p;length=[long]$item.Length}};@{schemaVersion=1;runId=$runId;startedAtUtc=$started.ToString('O');completedAtUtc=[DateTimeOffset]::UtcNow.ToString('O');manifest=@{path='docs/demo-package.json';sha256=Get-Sha256Hex $manifest};artifacts=$bound;scope='local-zero-cost';providerLiveEvidence=$false}|ConvertTo-Json -Depth 8|Set-Content $receipt -Encoding UTF8
 if(-not(Test-Path $receipt -PathType Leaf)-or(Get-Item $receipt).Length-le0){throw 'Preflight receipt was not materialized.'}
 Write-Host '==> Independently verifying run-bound receipt'; & $receiptVerifier -RepositoryRoot $root -ReceiptPath $receipt; if($LASTEXITCODE-ne0){throw "Independent receipt verification failed with exit code $LASTEXITCODE."}
 Write-Host '==> Provider-live checks skipped (zero-cost/fail-closed mode).';Write-Host 'Submission preflight PASS (local zero-cost scope).';Write-Host "Run-bound receipt: $receipt"
}finally{Pop-Location}
