using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Nvidea.Core.Capabilities;

namespace Nvidea.Core.Jobs;

public sealed record RemoteResearchStageResult(Guid LocalJobId,string InputCheckpointStep,string OpaqueWorkItemId,string RemoteJobId,JobStepResult StepResult,DateTimeOffset CompletedAt,DateTimeOffset ExpiresAt);
public sealed record ProtectedResearchResultEnvelope(string ProtocolVersion,string OpaqueWorkItemId,string RemoteJobId,string WrappedDataKey,string Nonce,string Ciphertext,string AuthenticationTag,DateTimeOffset CompletedAt,DateTimeOffset ExpiresAt);
public interface IProtectedResearchResultTransport { Task PutAsync(ProtectedResearchResultEnvelope envelope,CancellationToken cancellationToken=default); Task<ProtectedResearchResultEnvelope?> GetAsync(string opaqueWorkItemId,CancellationToken cancellationToken=default); Task DeleteAsync(string opaqueWorkItemId,CancellationToken cancellationToken=default); }

public static class ResearchResultProtector
{
    public const string ProtocolVersion="nvidea.research.remote-result.v1"; public const int MaxPlaintextBytes=2*1024*1024; public static readonly TimeSpan MaxLifetime=TimeSpan.FromHours(24); private const int DataKeyBytes=32,NonceBytes=12,TagBytes=16;
    public static ProtectedResearchResultEnvelope Protect(RemoteResearchStageResult result,string clientPublicKeyPem)
    {
        ValidateResult(result); using var rsa=ClientResultEnvelopePublicKeyTrust.CreateValidatedRsa(clientPublicKeyPem); var plaintext=JsonSerializer.SerializeToUtf8Bytes(result,new JsonSerializerOptions(JsonSerializerDefaults.Web)); if(plaintext.Length>MaxPlaintextBytes) throw new InvalidOperationException($"Remote research result exceeds the {MaxPlaintextBytes}-byte limit."); var dataKey=RandomNumberGenerator.GetBytes(DataKeyBytes); var nonce=RandomNumberGenerator.GetBytes(NonceBytes); var ciphertext=new byte[plaintext.Length]; var tag=new byte[TagBytes]; var aad=BuildAssociatedData(result.OpaqueWorkItemId,result.RemoteJobId,result.CompletedAt,result.ExpiresAt);
        try { using(var aes=new AesGcm(dataKey,TagBytes)) aes.Encrypt(nonce,plaintext,ciphertext,tag,aad); var wrapped=rsa.Encrypt(dataKey,RSAEncryptionPadding.OaepSHA256); return new(ProtocolVersion,result.OpaqueWorkItemId,result.RemoteJobId,Convert.ToBase64String(wrapped),Convert.ToBase64String(nonce),Convert.ToBase64String(ciphertext),Convert.ToBase64String(tag),result.CompletedAt,result.ExpiresAt); } finally { CryptographicOperations.ZeroMemory(dataKey); CryptographicOperations.ZeroMemory(plaintext); }
    }
    public static RemoteResearchStageResult Unprotect(ProtectedResearchResultEnvelope envelope,string clientPrivateKeyPem,DateTimeOffset? now=null)
    {
        ArgumentNullException.ThrowIfNull(envelope); if(!string.Equals(envelope.ProtocolVersion,ProtocolVersion,StringComparison.Ordinal)) throw new InvalidOperationException("Unsupported remote research result protocol version."); ValidateOpaqueId(envelope.OpaqueWorkItemId); ValidateRemoteJobId(envelope.RemoteJobId); var current=now??DateTimeOffset.UtcNow; if(envelope.ExpiresAt<=current) throw new InvalidOperationException("Remote research result has expired."); if(envelope.ExpiresAt<=envelope.CompletedAt||envelope.ExpiresAt-envelope.CompletedAt>MaxLifetime) throw new InvalidOperationException("Remote research result lifetime is invalid."); using var rsa=ClientResultEnvelopePrivateKeyTrust.CreateValidatedRsa(clientPrivateKeyPem); var wrapped=DecodeBase64(envelope.WrappedDataKey,"wrapped data key"); var nonce=DecodeBase64(envelope.Nonce,"nonce"); var ciphertext=DecodeBase64(envelope.Ciphertext,"ciphertext"); var tag=DecodeBase64(envelope.AuthenticationTag,"authentication tag"); if(nonce.Length!=NonceBytes||tag.Length!=TagBytes||ciphertext.Length>MaxPlaintextBytes) throw new InvalidOperationException("Remote research result has invalid cryptographic dimensions."); var key=rsa.Decrypt(wrapped,RSAEncryptionPadding.OaepSHA256); if(key.Length!=DataKeyBytes){CryptographicOperations.ZeroMemory(key);throw new InvalidOperationException("Remote research result contains an invalid data key.");} var plaintext=new byte[ciphertext.Length];
        try { using(var aes=new AesGcm(key,TagBytes)) aes.Decrypt(nonce,ciphertext,tag,plaintext,BuildAssociatedData(envelope.OpaqueWorkItemId,envelope.RemoteJobId,envelope.CompletedAt,envelope.ExpiresAt)); var result=JsonSerializer.Deserialize<RemoteResearchStageResult>(plaintext,new JsonSerializerOptions(JsonSerializerDefaults.Web))??throw new InvalidOperationException("Remote research result payload is empty."); ValidateResult(result); if(!string.Equals(result.OpaqueWorkItemId,envelope.OpaqueWorkItemId,StringComparison.Ordinal)||!string.Equals(result.RemoteJobId,envelope.RemoteJobId,StringComparison.Ordinal)||result.CompletedAt!=envelope.CompletedAt||result.ExpiresAt!=envelope.ExpiresAt) throw new CryptographicException("Remote research result provenance does not match the protected payload."); return result; } finally { CryptographicOperations.ZeroMemory(key); CryptographicOperations.ZeroMemory(plaintext); }
    }
    private static void ValidateResult(RemoteResearchStageResult r){ArgumentNullException.ThrowIfNull(r);if(r.LocalJobId==Guid.Empty)throw new ArgumentException("Local research job id is required.",nameof(r));if(string.IsNullOrWhiteSpace(r.InputCheckpointStep)||r.InputCheckpointStep.Length>128)throw new ArgumentException("A bounded input checkpoint step is required.",nameof(r));ValidateOpaqueId(r.OpaqueWorkItemId);ValidateRemoteJobId(r.RemoteJobId);ArgumentNullException.ThrowIfNull(r.StepResult);if(r.ExpiresAt<=r.CompletedAt||r.ExpiresAt-r.CompletedAt>MaxLifetime)throw new ArgumentException("Remote research result must have a positive lifetime of no more than 24 hours.",nameof(r));}
    private static byte[] BuildAssociatedData(string o,string j,DateTimeOffset c,DateTimeOffset e)=>Encoding.UTF8.GetBytes(string.Join('\n',ProtocolVersion,o,j,c.ToUniversalTime().ToString("O"),e.ToUniversalTime().ToString("O")));
    private static void ValidateOpaqueId(string v){if(string.IsNullOrWhiteSpace(v)||v.Length<24||v.Length>64||v.Any(static ch=>!(char.IsLetterOrDigit(ch)||ch is '-' or '_')))throw new InvalidOperationException("Remote research work-item id is invalid.");}
    private static void ValidateRemoteJobId(string v){if(string.IsNullOrWhiteSpace(v)||v.Length>256||v.Any(char.IsControl))throw new InvalidOperationException("Remote research job id is invalid.");}
    private static byte[] DecodeBase64(string v,string n){if(string.IsNullOrWhiteSpace(v))throw new InvalidOperationException($"Remote research result {n} is missing.");try{return Convert.FromBase64String(v);}catch(FormatException ex){throw new InvalidOperationException($"Remote research result {n} is malformed.",ex);}}
}

public sealed class NebiusResearchWorker
{
    private readonly IProtectedResearchWorkItemTransport _workItems; private readonly IProtectedResearchResultTransport _results; private readonly ResearchJobHandler _handler; private readonly string _workerPrivateKeyPem; private readonly string _clientPublicKeyPem;
    public NebiusResearchWorker(IProtectedResearchWorkItemTransport workItems,IProtectedResearchResultTransport results,ResearchJobHandler handler,string workerPrivateKeyPem,string clientPublicKeyPem){_workItems=workItems??throw new ArgumentNullException(nameof(workItems));_results=results??throw new ArgumentNullException(nameof(results));_handler=handler??throw new ArgumentNullException(nameof(handler));_workerPrivateKeyPem=string.IsNullOrWhiteSpace(workerPrivateKeyPem)?throw new ArgumentException("Worker private key is required.",nameof(workerPrivateKeyPem)):workerPrivateKeyPem;_clientPublicKeyPem=string.IsNullOrWhiteSpace(clientPublicKeyPem)?throw new ArgumentException("Client public key is required.",nameof(clientPublicKeyPem)):clientPublicKeyPem;}
    public async Task<ProtectedResearchResultEnvelope> ExecuteOneStageAsync(string opaqueWorkItemId,string remoteJobId,CancellationToken cancellationToken=default)
    { if(string.IsNullOrWhiteSpace(opaqueWorkItemId))throw new ArgumentException("Opaque work-item id is required.",nameof(opaqueWorkItemId));if(string.IsNullOrWhiteSpace(remoteJobId))throw new ArgumentException("Remote job id is required.",nameof(remoteJobId));var envelope=await _workItems.GetAsync(opaqueWorkItemId,cancellationToken).ConfigureAwait(false)??throw new InvalidOperationException("Remote research work item was not found.");if(!string.Equals(envelope.OpaqueWorkItemId,opaqueWorkItemId,StringComparison.Ordinal))throw new CryptographicException("Retrieved work item does not match the requested opaque id.");var workItem=ResearchWorkItemProtector.Unprotect(envelope,_workerPrivateKeyPem);if(workItem.ContainsPrivateOsData)throw new InvalidOperationException("Private OS-local research must not execute remotely.");var checkpoint=new AgentJobCheckpoint(workItem.CheckpointStep,workItem.CheckpointPayload,workItem.CreatedAt);var definition=new AgentJobDefinition(ResearchJobHandler.Type,"research.deep",new HashSet<DataPermission>{DataPermission.NetworkAccess},CapabilityRiskLevel.Low,false,true);var record=new AgentJobRecord(workItem.LocalJobId,definition,AgentJobState.Running,JobExecutionLocation.NebiusServerless,1,checkpoint,null,null,workItem.CreatedAt,DateTimeOffset.UtcNow);var stepResult=await _handler.ExecuteStepAsync(record,cancellationToken).ConfigureAwait(false);if(stepResult.RequiresApproval||!string.IsNullOrWhiteSpace(stepResult.ApprovalScope))throw new InvalidOperationException("Remote research worker cannot publish an approval-bearing stage result.");if(string.IsNullOrWhiteSpace(stepResult.CheckpointStep))throw new InvalidOperationException("Remote research stage did not produce a checkpoint step.");var completedAt=DateTimeOffset.UtcNow;var result=new RemoteResearchStageResult(workItem.LocalJobId,workItem.CheckpointStep,opaqueWorkItemId,remoteJobId,stepResult,completedAt,completedAt.Add(ResearchResultProtector.MaxLifetime));var protectedResult=ResearchResultProtector.Protect(result,_clientPublicKeyPem);await _results.PutAsync(protectedResult,cancellationToken).ConfigureAwait(false);return protectedResult;}
}
