namespace Nvidea.Core.Jobs;

public sealed class ResearchDispatchBindingCleanup
{
    private readonly IProtectedResearchDispatchBindingTransport _transport;
    public ResearchDispatchBindingCleanup(IProtectedResearchDispatchBindingTransport transport) => _transport = transport ?? throw new ArgumentNullException(nameof(transport));
    public async Task TryCleanupIfTerminalAsync(AgentJobRecord job) { ArgumentNullException.ThrowIfNull(job); var p = job.RemoteResearch; if (p is null || !CanDeleteBinding(job, p)) return; try { await _transport.DeleteAsync(p.OpaqueWorkItemId, CancellationToken.None).ConfigureAwait(false); } catch { } }
    public static bool CanDeleteBinding(AgentJobRecord job, RemoteResearchProvenance p) { ArgumentNullException.ThrowIfNull(job); ArgumentNullException.ThrowIfNull(p); if (job.ExecutionLocation != JobExecutionLocation.Local) return false; return p.State switch { RemoteResearchProvenanceState.ResultApplied => job.State is AgentJobState.Pending or AgentJobState.Completed, RemoteResearchProvenanceState.Cancelled => job.State == AgentJobState.Cancelled, RemoteResearchProvenanceState.RemoteFailed or RemoteResearchProvenanceState.Expired => job.State == AgentJobState.Failed, _ => false }; }
}

public sealed class NebiusResearchClientRuntime : IRemoteResearchClientRuntime
{
    private readonly ResearchDispatchBindingCleanup _bindingCleanup; private readonly ResearchDispatchBindingRecovery _bindingRecovery;
    private NebiusResearchClientRuntime(TwoPhaseNebiusResearchDispatcher d, NebiusResearchLifecycleReconciler r, RemoteResearchResultIngestor i, ResearchDispatchBindingPublisher p, ResearchDispatchBindingRecovery br, ResearchDispatchBindingCleanup bc) { Dispatcher=d; Reconciler=r; Ingestor=i; BindingPublisher=p; _bindingRecovery=br; _bindingCleanup=bc; }
    public TwoPhaseNebiusResearchDispatcher Dispatcher { get; } public NebiusResearchLifecycleReconciler Reconciler { get; } public RemoteResearchResultIngestor Ingestor { get; } public ResearchDispatchBindingPublisher BindingPublisher { get; }
    public static NebiusResearchClientRuntime Create(JsonAgentJobStore store, INebiusServerlessJobClient serverless, IProtectedResearchWorkItemTransport workItems, IProtectedResearchResultTransport results, IProtectedResearchDispatchBindingTransport bindings, NebiusResearchDispatchOptions options, string clientPrivateKeyPem, Nvidea.Core.Capabilities.IAuditTrail auditTrail, string? clientResultPrivateKeyPem=null)
    {
        ArgumentNullException.ThrowIfNull(store); ArgumentNullException.ThrowIfNull(serverless); ArgumentNullException.ThrowIfNull(workItems); ArgumentNullException.ThrowIfNull(results); ArgumentNullException.ThrowIfNull(bindings); ArgumentNullException.ThrowIfNull(options); ArgumentNullException.ThrowIfNull(auditTrail); if (string.IsNullOrWhiteSpace(clientPrivateKeyPem)) throw new ArgumentException("Client private key is required.", nameof(clientPrivateKeyPem));
        var resultKey=string.IsNullOrWhiteSpace(clientResultPrivateKeyPem)?clientPrivateKeyPem:clientResultPrivateKeyPem; var publisher=new ResearchDispatchBindingPublisher(bindings,clientPrivateKeyPem); var atomic=new AtomicRemoteResearchDispatchReservation(store,auditTrail); var ingestor=new RemoteResearchResultIngestor(store,results,resultKey,auditTrail,workItems); var dispatcher=new TwoPhaseNebiusResearchDispatcher(serverless,workItems,options,bindingPublisher:publisher,envelopeCommitment:new DurableResearchEnvelopeCommitment(store),atomicReservation:atomic); var reconciler=new NebiusResearchLifecycleReconciler(store,serverless,ingestor,auditTrail); var obligation=new DurableResearchDispatchBindingObligation(store,publisher); return new NebiusResearchClientRuntime(dispatcher,reconciler,ingestor,publisher,new ResearchDispatchBindingRecovery(store,publisher,obligation),new ResearchDispatchBindingCleanup(bindings));
    }
    public Task<AgentJobRecord> DispatchAsync(RemoteResearchWorkItem w, ResearchCloudAuthorization a, CancellationToken c=default)=>Dispatcher.DispatchWithReservationAsync(w,a,Ingestor,c);
    public async Task<AgentJobRecord> ReconcileReservedAsync(Guid id,CancellationToken c=default){try{return await Dispatcher.ResumeReservedAsync(id,Ingestor,c).ConfigureAwait(false);}catch(RemoteResearchDispatchReservationRecoveryNotRequiredException){} var a=await Reconciler.ReconcileReservedAsync(id,c).ConfigureAwait(false); if(a.ExecutionLocation==JobExecutionLocation.NebiusServerless&&a.RemoteResearch is {State:RemoteResearchProvenanceState.Dispatched}) await _bindingRecovery.EnsureAsync(id,c).ConfigureAwait(false); return a;}
    public async Task<AgentJobRecord> ReconcileDispatchedAsync(Guid id,DateTimeOffset? now=null,CancellationToken c=default){var x=await TryRecoverAppliedResultAsync(id,c).ConfigureAwait(false);if(x is not null)return x;await _bindingRecovery.EnsureAsync(id,c).ConfigureAwait(false);var r=await Reconciler.ReconcileDispatchedAsync(id,now,c).ConfigureAwait(false);await _bindingCleanup.TryCleanupIfTerminalAsync(r).ConfigureAwait(false);return r;}
    public async Task<AgentJobRecord> RequestCancellationAsync(Guid id,CancellationToken c=default){await Ingestor.RecoverPendingAuditAsync(id,c).ConfigureAwait(false);await _bindingRecovery.EnsureAsync(id,c).ConfigureAwait(false);return await Reconciler.RequestCancellationAsync(id,c).ConfigureAwait(false);}
    public async Task<AgentJobRecord> ReconcileCancellationAsync(Guid id,CancellationToken c=default){var x=await TryRecoverAppliedResultAsync(id,c).ConfigureAwait(false);if(x is not null)return x;await _bindingRecovery.EnsureAsync(id,c).ConfigureAwait(false);var r=await Reconciler.ReconcileCancellationAsync(id,c).ConfigureAwait(false);await _bindingCleanup.TryCleanupIfTerminalAsync(r).ConfigureAwait(false);return r;}
    public async Task<AgentJobRecord> RecoverPendingAuditAsync(Guid id,CancellationToken c=default){var r=await Ingestor.RecoverPendingAuditAsync(id,c).ConfigureAwait(false);await _bindingCleanup.TryCleanupIfTerminalAsync(r).ConfigureAwait(false);return r;}
    public async Task<AgentJobRecord> IngestAsync(Guid id,DateTimeOffset? now=null,CancellationToken c=default){var r=await Ingestor.IngestAsync(id,now,c).ConfigureAwait(false);await _bindingCleanup.TryCleanupIfTerminalAsync(r).ConfigureAwait(false);return r;}
    private async Task<AgentJobRecord?> TryRecoverAppliedResultAsync(Guid id,CancellationToken c){var r=await Ingestor.RecoverPendingAuditAsync(id,c).ConfigureAwait(false);if(r.ExecutionLocation!=JobExecutionLocation.Local||r.RemoteResearch is not {State:RemoteResearchProvenanceState.ResultApplied})return null;await _bindingCleanup.TryCleanupIfTerminalAsync(r).ConfigureAwait(false);return r;}
}
