using System.Security.Cryptography;
using Nvidea.Core.Jobs;

namespace Nvidea.Core.Tests;

public sealed class NebiusResearchResultProtocolTests
{
    [Fact] public void ResultProtector_RoundTripsCheckpointWithoutPlaintextLeakage(){using var rsa=RSA.Create(2048);var now=DateTimeOffset.UtcNow;var result=ValidResult(now) with{StepResult=new JobStepResult(false,ResearchJobHandler.EvidenceStep,"{\"question\":\"sensitive roadmap question\",\"evidence\":\"private source material\"}")};var envelope=ResearchResultProtector.Protect(result,rsa.ExportSubjectPublicKeyInfoPem());var serialized=System.Text.Json.JsonSerializer.Serialize(envelope);Assert.DoesNotContain("sensitive roadmap question",serialized,StringComparison.Ordinal);Assert.DoesNotContain("private source material",serialized,StringComparison.Ordinal);Assert.Equal(result,ResearchResultProtector.Unprotect(envelope,rsa.ExportPkcs8PrivateKeyPem(),now.AddMinutes(1)));}
    [Fact] public void ResultProtector_RejectsRemoteJobIdTampering(){using var rsa=RSA.Create(2048);var now=DateTimeOffset.UtcNow;var e=ResearchResultProtector.Protect(ValidResult(now),rsa.ExportSubjectPublicKeyInfoPem());Assert.Throws<CryptographicException>(()=>ResearchResultProtector.Unprotect(e with{RemoteJobId="aijob-substituted"},rsa.ExportPkcs8PrivateKeyPem(),now.AddMinutes(1)));}
    [Fact] public void ResultProtector_RejectsOpaqueWorkItemSwap(){using var rsa=RSA.Create(2048);var now=DateTimeOffset.UtcNow;var e=ResearchResultProtector.Protect(ValidResult(now),rsa.ExportSubjectPublicKeyInfoPem());var id=e.OpaqueWorkItemId[..^1]+(e.OpaqueWorkItemId[^1]=='A'?"B":"A");Assert.Throws<CryptographicException>(()=>ResearchResultProtector.Unprotect(e with{OpaqueWorkItemId=id},rsa.ExportPkcs8PrivateKeyPem(),now.AddMinutes(1)));}
    [Fact] public void ResultProtector_RejectsCiphertextMutationIncludingCheckpointReceiptPayload(){using var rsa=RSA.Create(2048);var now=DateTimeOffset.UtcNow;var result=ValidResult(now) with{StepResult=new JobStepResult(true,ResearchJobHandler.CompletedStep,"{\"report\":{\"answerMarkdown\":\"trusted\"},\"receipt\":{\"reportSha256\":\"abc\",\"provenanceSha256\":\"def\"}}")};var e=ResearchResultProtector.Protect(result,rsa.ExportSubjectPublicKeyInfoPem());var c=Convert.FromBase64String(e.Ciphertext);c[c.Length/2]^=1;Assert.Throws<CryptographicException>(()=>ResearchResultProtector.Unprotect(e with{Ciphertext=Convert.ToBase64String(c)},rsa.ExportPkcs8PrivateKeyPem(),now.AddMinutes(1)));}
    [Fact] public void ResultProtector_RejectsCiphertextAndTagSubstitutionFromAnotherValidEnvelope(){using var rsa=RSA.Create(2048);var now=DateTimeOffset.UtcNow;var expected=ValidResult(now);var substituted=expected with{StepResult=new JobStepResult(true,ResearchJobHandler.CompletedStep,"{\"report\":\"substituted\",\"receipt\":\"substituted\"}")};var first=ResearchResultProtector.Protect(expected,rsa.ExportSubjectPublicKeyInfoPem());var second=ResearchResultProtector.Protect(substituted,rsa.ExportSubjectPublicKeyInfoPem());Assert.Throws<CryptographicException>(()=>ResearchResultProtector.Unprotect(first with{Ciphertext=second.Ciphertext,AuthenticationTag=second.AuthenticationTag},rsa.ExportPkcs8PrivateKeyPem(),now.AddMinutes(1)));}
    [Fact] public void ResultProtector_RejectsExpiredResultBeforeDecrypting(){using var rsa=RSA.Create(2048);var now=DateTimeOffset.UtcNow;var r=ValidResult(now);var e=ResearchResultProtector.Protect(r,rsa.ExportSubjectPublicKeyInfoPem());Assert.Throws<InvalidOperationException>(()=>ResearchResultProtector.Unprotect(e,rsa.ExportPkcs8PrivateKeyPem(),r.ExpiresAt.AddSeconds(1)));}
    private static RemoteResearchStageResult ValidResult(DateTimeOffset now)=>new(Guid.NewGuid(),ResearchJobHandler.PlannedStep,"mY7FhPlAdtPz9xL4b8gU1cKqN3sW6vRt","aijob-remote-123",new JobStepResult(false,ResearchJobHandler.EvidenceStep,"{\"prepared\":true}"),now,now.AddHours(2));
}
